# -*- coding: utf-8 -*-
"""Desafios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yxvG-Ab-S5gVMuVfAqoG7fn3nV3ajoJE

# Resolvendo Seus Primeiros Desafios de Código

## Desafio 1
"""

saldo_atual = float(input())
valor_deposito = float(input())
valor_retirada = float(input())

#TODO: Calcular o saldo atualizado de acordo com a descrição deste desafio.
saida = saldo_atual + valor_deposito - valor_retirada
#TODO: Imprimir o a saída de conforme a tabela de exemplos (uma casa decimal).
print('Saldo atualizado na conta:', round(saida, 2))

"""## Desafio 2

"""

ativos = []

# Entrada da quantidade de ativos
quantidadeAtivos = int(input())

# Entrada dos códigos dos ativos
for _ in range(quantidadeAtivos):
    codigoAtivo = input()
    ativos.append(codigoAtivo)

# TODO: Ordenar os ativos em ordem alfabética.
ordem = sorted(ativos)


# TODO: Imprimir a lista de ativos ordenada, conforme a tabela de exemplos.

print(*ordem, sep = "\n")

"""## Desafio 3"""

# Entrada de dados
saldo_total = int(input())
valor_saque = int(input())

# TODO: Criar as condições necessárias para impressão da saída, vide tabela de exemplos.
if saldo_total >= valor_saque:
  saldo = saldo_total - valor_saque
  print("Saque realizado com sucesso! Novo saldo:", saldo)
else:
  print("Saldo insuficiente. Saque nao realizado!")

"""## Desafio 4"""

valor_inicial = float(input())
taxa_juros = float(input())
periodo = int(input())

valor_final = valor_inicial

#TODO: Iterar, baseado no período em anos, para calculo do valorFinal com os juros.
montante = valor_inicial * ((1 + taxa_juros)**periodo)
print("Valor final do investimento: R$", round(montante, 2))

"""## Desafio 5"""

valor = float(input())

if valor > 0:
    print("Deposito realizado com sucesso! \n Saldo atual: R$ {:.02f}".format(valor, 2))
elif valor == 0:
   print("Encerrando o programa...")
else:
  print("Valor invalido! Digite um valor maior que zero.")

round(500.50, 3)
